//request:after header + data flag + ID SubID + extended
#define TNS_315_MAGICSHIFT_TO_USER_INFO (12+18)
#define TNS_315_MAGICSHIFT_TO_SQL_COMMAND1 (12+87)
#define TNS_315_MAGICSHIFT_TO_SQL_COMMAND2 (12+75)
//response:after header + data falg
#define TNS_312_MAGICSHIFT_TO_RESPONSE_USER_INFO (10+8)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_SQL (10+73)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_valid (10+24)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_invalid 0