//request:after header + data flag + ID SubID + extended
#define TNS_315_MAGICSHIFT_TO_USER_INFO (30)
#define TNS_315_MAGICSHIFT_TO_SQL_COMMAND1 (99)
#define TNS_315_MAGICSHIFT_TO_SQL_COMMAND2 (87)
//response:after header + data falg
#define TNS_312_MAGICSHIFT_TO_RESPONSE_USER_INFO (18)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_SQL (83)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_valid (34)
#define TNS_315_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_invalid 0
