//request:after header + data flag + ID SubID + extended
#define TNS_312_MAGICSHIFT_TO_USER_INFO (42)
#define TNS_312_MAGICSHIFT_TO_SQL_COMMAND1 (109)
#define TNS_312_MAGICSHIFT_TO_SQL_COMMAND2 (109)
//response:after header + data falg
#define TNS_312_MAGICSHIFT_TO_RESPONSE_USER_INFO (18)
#define TNS_312_MAGICSHIFT_TO_RESPONSE_SQL (84)
#define TNS_312_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_valid (42)
#define TNS_312_MAGICSHIFT_TO_RESPONSE_FETCH_MORE_invalid 0
